### ISSUE TITLE
도커라이즈

### ISSUE THREAD

**Issue by wooogy-dev** [DPS0340/DjangoCRUDBoard#83]
백엔드 도커라이즈
- [ ] django, nginx, makemigration, migrate 도커라이즈
- [ ] database 도커라이즈
- [ ] prometheus, grafana, cadvisor, node-exporter 도커라이즈

**Comment by DPS0340** [comment]
- [X] django, nginx, makemigration, migrate 도커라이즈
- [X] database 도커라이즈
- [X] prometheus, grafana 도커라이즈
- [ ] ELK 스택 도커라이즈

**Comment by DPS0340** [comment]
- [X] ELK 스택 도커라이즈
