### ISSUE TITLE
api, model 리팩토링

### ISSUE THREAD

**Issue by wooogy-dev** [DPS0340/DjangoCRUDBoard#86]
- [x] queryset에 len함수를 활용해 결과값을 int형 필드를 만들어 넣는다
- [ ] 게시판을 /name으로 get 할 수 있게 수정
- [x] 게시판에 종속된 게시글에 대해 고유넘버 분리
- [x] 게시글에 종속된 댓글에 대해 고유넘버 분리
- [x] 댓글에 종속된 대댓글에 대해 고유넘버 분리

**Comment by DPS0340** [comment]
- [X] queryset에 len함수를 활용해 결과값을 int형 필드를 만들어 넣는다

**Comment by DPS0340** [comment]
- [X] 게시판에 종속된 게시글에 대해 고유넘버 분리
- [X] 게시글에 종속된 댓글에 대해 고유넘버 분리
- [X] 댓글에 종속된 대댓글에 대해 고유넘버 분리
